name: TypeScript CI
on:
  push:
    branches:
      - main
    paths:
      - typescript/**
      - specs/**
      - .github/workflows/typescript.yaml
      - codecov.yml
  pull_request:
    branches:
      - main
    paths:
      - typescript/**
      - specs/**
      - .github/workflows/typescript.yaml
      - codecov.yml
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.18.0'
      - name: Set up node
        run: |
          cd typescript
          npm ci --prefer-offline -no-audit
      - name: Run the automated tests
        run: |
          cd typescript
          npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@303a32d7a59b442fa8d48b6a1cc6825c09c847a5 # v7.1.1
        with:
          files: typescript/coverage/lcov.info
          flags: typescript
          fail_ci_if_error: true
          disable_search: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
      

  integration-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.18.0'
      - name: Set up node
        run: |
          cd typescript
          npm ci --prefer-offline -no-audit
      - name: Run build
        run: |
          python3 scripts/src/load/merge_data.py -o ./typescript/resources/merged_data.json
          cd typescript
          npm run build
      - name: Link package
        run: |
          cd typescript
          npm link
      - name: Run smoke tests against linked package
        working-directory: typescript
        run: npm run test:smoke
      - name: Test packed package
        working-directory: typescript
        run: npm run test:package

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '24.18.0'
      - name: Set up node
        run: |
          cd typescript
          npm ci --prefer-offline -no-audit
      - name: Run linting
        run: |
          cd typescript
          npm run lint
